/* tracegen: build an input trace (.mmin) by driving the core closed-loop.
 *
 *   tracegen ROM [--load-state S --state-frame N] < script > out.mmin
 *
 * Script commands (one per line, '#' comments):
 *   wait N              no input for N frames
 *   press BUTTONS N     hold BUTTONS (A, B, START+A, ...) for N frames, then release
 *   seek SPRITE X Y     move the pointer (OAM entry SPRITE) with the D-pad
 *                       until it is within 2 px of (X, Y); tap near the end
 *   untilchange N       wait (no input) until the frame changes, at most N frames
 *
 * The emitted trace is plain frame/button data: replaying it in the port or
 * in a reference emulator reproduces the same run. Frame numbers are
 * absolute from power-on (or from --state-frame when resuming a state). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

#include "../src/core/cart.h"
#include "../src/core/nes.h"

static nes_t nes;
static long frame;
static uint8_t last_out = 0xFF;

static const struct { const char *n; uint8_t b; } names[] = {
    {"A", PAD_A}, {"B", PAD_B}, {"SELECT", PAD_SELECT}, {"START", PAD_START},
    {"UP", PAD_UP}, {"DOWN", PAD_DOWN}, {"LEFT", PAD_LEFT}, {"RIGHT", PAD_RIGHT},
};

static void emit(uint8_t b)
{
    if (b == last_out)
        return;
    last_out = b;
    printf("%ld ", frame);
    if (!b) {
        puts("-");
        return;
    }
    bool first = true;
    for (size_t i = 0; i < 8; i++)
        if (b & names[i].b) {
            printf("%s%s", first ? "" : "+", names[i].n);
            first = false;
        }
    putchar('\n');
}

static void step(uint8_t b)
{
    emit(b);
    nes_set_pad(&nes, 0, b);
    nes_run_frame(&nes);
    frame++;
}

static uint8_t parse(char *s)
{
    uint8_t b = 0;
    for (char *t = strtok(s, "+"); t; t = strtok(NULL, "+"))
        for (size_t i = 0; i < 8; i++)
            if (!strcasecmp(t, names[i].n))
                b |= names[i].b;
    return b;
}

static int fb_changed(const uint16_t *a, const uint16_t *b)
{
    return memcmp(a, b, sizeof nes.ppu.fb) != 0;
}

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: tracegen ROM [--load-state S --state-frame N] < script\n");
        return 2;
    }
    cart_t c;
    char err[512];
    if (!cart_load(&c, argv[1], false, err, sizeof err)) {
        fprintf(stderr, "%s\n", err);
        return 2;
    }
    nes_init(&nes, c.prg, c.prg_size);
    nes_power(&nes, 0);
    for (int i = 2; i + 1 < argc; i += 2) {
        if (!strcmp(argv[i], "--state-frame"))
            frame = strtol(argv[i + 1], NULL, 10);
        else if (!strcmp(argv[i], "--load-state")) {
            static uint8_t buf[sizeof(nes_t) + 64];
            FILE *f = fopen(argv[i + 1], "rb");
            size_t n = f ? fread(buf, 1, sizeof buf, f) : 0;
            if (f)
                fclose(f);
            uint8_t id[8];
            for (int k = 0; k < 8; k++) {
                unsigned v;
                sscanf(c.prg_sha256 + k * 2, "%2x", &v);
                id[k] = (uint8_t)v;
            }
            if (!nes_state_load(&nes, buf, n, id)) {
                fprintf(stderr, "cannot load state\n");
                return 2;
            }
        }
    }
    printf("# generated by port/tools/tracegen\n");
    char line[256];
    static uint16_t prev[NES_W * NES_H];
    while (fgets(line, sizeof line, stdin)) {
        char *h = strchr(line, '#');
        if (h)
            *h = 0;
        char cmd[32], a1[64] = "", a2[32] = "", a3[32] = "";
        int k = sscanf(line, "%31s %63s %31s %31s", cmd, a1, a2, a3);
        if (k <= 0)
            continue;
        printf("# %s %s %s %s\n", cmd, a1, a2, a3);
        if (!strcmp(cmd, "wait")) {
            for (long n = strtol(a1, NULL, 10); n > 0; n--)
                step(0);
        } else if (!strcmp(cmd, "press")) {
            uint8_t b = parse(a1);
            for (long n = strtol(a2, NULL, 10); n > 0; n--)
                step(b);
            step(0);
        } else if (!strcmp(cmd, "untilchange")) {
            memcpy(prev, nes.ppu.fb, sizeof prev);
            for (long n = strtol(a1, NULL, 10); n > 0 && !fb_changed(prev, nes.ppu.fb); n--)
                step(0);
        } else if (!strcmp(cmd, "seek")) {
            int s = atoi(a1), tx = atoi(a2), ty = atoi(a3);
            for (int guard = 0; guard < 600; guard++) {
                int x = nes.ppu.oam[s * 4 + 3], y = nes.ppu.oam[s * 4];
                int dx = tx - x, dy = ty - y;
                if (abs(dx) <= 2 && abs(dy) <= 2)
                    break;
                uint8_t b = 0;
                if (dx > 2) b |= PAD_RIGHT;
                if (dx < -2) b |= PAD_LEFT;
                if (dy > 2) b |= PAD_DOWN;
                if (dy < -2) b |= PAD_UP;
                /* near the target, tap (press one frame, release one) to
                 * defeat the pointer's acceleration */
                if (abs(dx) < 12 && abs(dy) < 12 && (frame & 1))
                    b = 0;
                step(b);
            }
            step(0);
            fprintf(stderr, "seek %d -> (%d,%d) reached (%d,%d) at frame %ld\n", s, tx, ty, nes.ppu.oam[s * 4 + 3],
                    nes.ppu.oam[s * 4], frame);
        } else {
            fprintf(stderr, "unknown command '%s'\n", cmd);
            return 2;
        }
    }
    emit(0);
    printf("end %ld\n", frame);
    return 0;
}
